services:
  isza-screenshots:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NUM_RETRIES=1
      - DAILY_POST_TIME_EST=12:15pm
    command: gunicorn -w 2 -b 0.0.0.0:8000 app:app
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/var

  cloudflared:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
