version: '3.8'
services:
  isza-screenshots:
    container_name: isza-screenshots
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../env.master
    environment:
      - NUM_RETRIES=1
      - DAILY_POST_TIME_EST=12:15pm
    ports:
      - ${ISZASC_SERVER_PORT}:8000
    command: gunicorn -w 2 -b 0.0.0.0:8000 app:app
    volumes:
      - ./instance/posts.db:/app/instance/posts.db
      - ./uploads:/app/var
