name: Daily Post Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  make-post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Curl Command
      run: |
        response=$(curl --location --request GET "https://btschwartz.com/icestation/api/post?secret=pruh-juh-4$&test=true" -w '%{http_code}' -o /dev/null -s)
        if [ "$response" -ne 200 ]; then
          echo "Request failed with status $response"
          exit 1
        fi